trigger:
  branches:
    include:
      - 'main'

pr:
  branches:
    include:
      - 'main'

pool:
  name: "aws-agents-pool"

variables:
  imageName: 'aishafathy/nodeapp:latest'

stages:
  - stage: Setup
    displayName: 'Setup Environment'
    jobs:
      - job: AWS_Setup
        displayName: 'Setup AWS Environment'
        steps:
          - checkout: self
          - task: AWSShellScript@1
            inputs:
              awsCredentials: 'AWS Service Connection'
              regionName: 'us-east-1'
              scriptType: 'inline'
              inlineScript: |
                sudo apt-get update
                sudo apt-get install -y unzip jq

      - job: Terraform_Installation
        displayName: 'Install Terraform'
        steps:
          - checkout: self
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

  - stage: Plan
    displayName: 'Plan Terraform'
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - job: Terraform_Initialization
        displayName: 'Initialize Terraform'
        steps:
          - checkout: self
          - task: TerraformTaskV4@4
            inputs:
              provider: 'aws'
              command: 'init'
              backendServiceAWS: 'aws_for_terraform'
              backendAWSBucketName: 's3-terraform-backend-bucket-123456'
              backendAWSKey: 'terraform.tfstate'

      - job: Terraform_Plan
        displayName: 'Terraform Plan'
        steps:
          - checkout: self
          - task: TerraformTaskV4@4
            inputs:
              provider: 'aws'
              command: 'plan'
              commandOptions: '-var-file=terraform.tfvars'
              environmentServiceNameAWS: 'aws_for_terraform'

  - stage: Apply
    displayName: 'Apply Terraform'
    condition: or(
      and(eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.SourceBranch'], 'refs/heads/main')),
      and(ne(variables['Build.Reason'], 'Manual'), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
      )
    jobs:
      - job: Terraform_Initialization
        displayName: 'Initialize Terraform'
        steps:
          - checkout: self
          - task: TerraformTaskV4@4
            inputs:
              provider: 'aws'
              command: 'init'
              backendServiceAWS: 'aws_for_terraform'
              backendAWSBucketName: 's3-terraform-backend-bucket-123456'
              backendAWSKey: 'terraform.tfstate'

      - job: Terraform_Apply
        displayName: 'Terraform Apply'
        steps:
          - checkout: self
          # - task: TerraformTaskV4@4
          #   inputs:
          #     provider: 'aws'
          #     command: 'apply'
          #     commandOptions: '-var-file=terraform.tfvars --auto-approve'
          #     environmentServiceNameAWS: 'aws_for_terraform'
