# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - 'main'

pr:
  branches:
    include:
      - 'main'

pool:
  name: "aws-agents-pool"

stages:
  - stage: Plan
    displayName: 'Plan Terraform'
    jobs:
      - job: Plan
        displayName: 'Terraform Plan'
        steps:
          - checkout: self
          - task: TerraformTaskV1@0
            inputs:
              provider: 'aws' 
              command: 'init'
          - task: TerraformTaskV1@0
            inputs:
              provider: 'aws' 
              command: 'plan'
              commandOptions: '-out=tfplan -input=false'
