trigger:
  branches:
    include: 
      - 'nodejs-app'

pool:
  name: aws-agents-pool  

variables:
  imageName: 'aishafathy/nodeapp:latest' 

stages:
  - stage: install_docker
    displayName: 'Install Docker'
    jobs:
      - job: InstallDockerJob
        displayName: 'Install Docker'
        steps:
          - task: DockerInstaller@0
            inputs:
              dockerVersion: '17.09.0-ce'

  - stage: Login
    displayName: 'Docker Login'
    dependsOn: install_docker
    jobs:
      - job: LoginJob
        displayName: 'Login to Docker Hub'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'docker-hub'
              command: 'login'

  - stage: BuildAndPush
    displayName: 'Build and Push Docker Image'
    dependsOn: Login
    jobs:
      - job: BuildAndPushJob
        displayName: 'Build and Push'
        steps:
          - checkout: self
          - task: Docker@2
            inputs:
              containerRegistry: 'docker-hub'
              repository: 'aishafathy/nodeapp'
              command: 'buildAndPush'
              tags: 'latest'

  - stage: Deploy
    displayName: 'Deploy Docker Container'
    dependsOn: BuildAndPush
    jobs:
      - job: DeployJob
        displayName: 'Deploy'
        steps:
          - checkout: self
          - task: Docker@2
            inputs:
              containerRegistry: 'docker-hub'
              repository: 'aishafathy/nodeapp'
              command: 'start'
              arguments: '-d -p 8080:80 $(imageName)'
